name: genai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.14
  - pip
  - faiss-cpu=1.8.0
  - streamlit=1.34.0
  - pypdf=4.2.0
  - lxml=5.2.1
  - openssl
  - sqlite
  - libffi
  - zlib
  - cffi
  - libpython
  - wheel
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - jupyterlab
  - ipywidgets
  - notebook
  - matplotlib-inline
  - pyzmq
  - tk
  - tbb
  - libprotobuf
  - grpc-cpp
  - abseil-cpp
  - pip:
      - langchain==0.1.17
      - langchain-core==0.1.50
      - langchain-community==0.0.34
      - huggingface-hub==0.21.4
      - transformers==4.41.0
      - sentence-transformers==2.7.0
      - openai==1.30.1
      - unstructured==0.13.1
      - streamlit-chat==0.1.1
      - google-cloud-aiplatform==1.43.0
      - google-api-core==2.18.0
      - vertexai==0.0.1
      - beautifulsoup4==4.12.3
      - python-dotenv==1.0.1
      - tiktoken==0.7.0
      - aiohttp==3.9.3
      - fastapi==0.111.0
      - uvicorn==0.30.0
      - pydantic==2.7.1
      - pydantic-settings==2.2.1
      - requests==2.32.2
      - tqdm==4.66.2
      - regex==2023.12.25
      - rich==13.7.1
